version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule: 
      interval: weekly
      day: friday
    groups:
      minor:
        exclude-patterns:
          - file-owner # pre 1.0
        update-types:
          - minor
          - patch
    reviewers:
      - TeFiLeDo
