[package]
name = "tree-owners"
version = "0.1.0"
edition = "2021"
authors = ["Adrian Wannenmacher <tfld@tfld.dev>"]
description = "Find all owners (user and group) inside a directory tree."
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.4", features = ["derive", "cargo", "wrap_help"] }
file-owner = "0.1.2"
human-panic = "1.2.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
