name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Adjust compiler output
        run: mv ../ci-out/_tree-owners ../ci-out/tree-owners.zsh
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: github.event_name == 'push'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            target/debug/tree-owners
            ../ci-out/tree-owners.bash
            ../ci-out/tree-owners.fish
            ../ci-out/tree-owners.zsh
